### ISSUE TITLE
Pagination Broken

### ISSUE THREAD

**Issue by jakeanq** [mosra/magnum-website#9]
Links to next and previous pages on paginated pages (for example on https://blog.magnum.graphics/ ) do not work as the URL becomes https://magnum.graphics/blog.magnum.graphics/2/ instead of https://blog.magnum.graphics/2/

**Comment by mosra** [comment]
Thanks a lot for reporting this, very appreciated. Should be fixed now.

(For the record, turns out it was a regression in Pelican: https://github.com/getpelican/pelican/pull/2503)
